server.port=${PORT:8081}

spring.application.name=user-service

# PostgreSQL
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/socialmedia_userdb}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=https://social-media-microservices-xhq9.onrender.com/eureka/

# Actuator
management.endpoints.web.exposure.include=health,info